# Generated by Django 6.0.4 on 2026-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=200)),
                ("org", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "RUNNING"), ("archived", "ARCHIVED")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("github_url", models.URLField()),
                ("stars", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ml_ai", "ML & AI"),
                            ("tools", "Tools"),
                            ("data", "Data"),
                            ("languages", "Languages"),
                        ],
                        max_length=20,
                    ),
                ),
                ("proficiency", models.IntegerField(help_text="0-100")),
            ],
        ),
    ]
