# Generated by Django 6.0.4 on 2026-04-27 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("ip_hash", models.CharField(max_length=64)),
                ("user_agent", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("section", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "SENT"),
                            ("READ", "READ"),
                            ("REPLIED", "REPLIED"),
                        ],
                        default="SENT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="experience",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="Git commit hash",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pid",
            field=models.CharField(
                blank=True,
                help_text="Process ID for terminal look",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("RUNNING", "RUNNING"), ("ARCHIVED", "ARCHIVED")],
                default="RUNNING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("ml_ai", "ML & AI"),
                    ("tools", "Tools"),
                    ("data", "Data"),
                    ("languages", "Languages"),
                    ("backend", "Backend"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="api.tag"
            ),
        ),
    ]
