web: daphne -b 0.0.0.0 -p $PORT portfolio.asgi:application
worker: celery -A portfolio worker --loglevel=info
beat: celery -A portfolio beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
